// <auto-generated />
using System;
using EventRegistrationSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventRegistrationSystem.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220224180704_cret_tbl")]
    partial class cret_tbl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventRegistrationSystemModels.Event_Registration", b =>
                {
                    b.Property<int>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Events")
                        .HasColumnType("int");

                    b.Property<int?>("Permissions")
                        .HasColumnType("int");

                    b.Property<int>("booking_seat_count")
                        .HasColumnType("int");

                    b.Property<string>("customer_email_phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("event_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("identificationd_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("booking_id");

                    b.HasIndex("Events");

                    b.HasIndex("Permissions");

                    b.ToTable("T_Event_Registration");
                });

            modelBuilder.Entity("EventRegistrationSystemModels.Events", b =>
                {
                    b.Property<int>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Ref_Event_Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("event_end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("event_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("event_start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("event_id");

                    b.HasIndex("Ref_Event_Type");

                    b.ToTable("T_Events");
                });

            modelBuilder.Entity("EventRegistrationSystemModels.Permissions", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("permission_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("permission_id");

                    b.ToTable("T_Permissions");
                });

            modelBuilder.Entity("EventRegistrationSystemModels.Ref_Event_Type", b =>
                {
                    b.Property<int>("event_type_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("event_type_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("event_type_code");

                    b.ToTable("T_Ref_Event_Type");
                });

            modelBuilder.Entity("EventRegistrationSystemModels.Event_Registration", b =>
                {
                    b.HasOne("EventRegistrationSystemModels.Events", "event_id")
                        .WithMany()
                        .HasForeignKey("Events");

                    b.HasOne("EventRegistrationSystemModels.Permissions", "permission_id")
                        .WithMany()
                        .HasForeignKey("Permissions");

                    b.Navigation("event_id");

                    b.Navigation("permission_id");
                });

            modelBuilder.Entity("EventRegistrationSystemModels.Events", b =>
                {
                    b.HasOne("EventRegistrationSystemModels.Ref_Event_Type", "event_type_code")
                        .WithMany()
                        .HasForeignKey("Ref_Event_Type");

                    b.Navigation("event_type_code");
                });
#pragma warning restore 612, 618
        }
    }
}
